name: 'Ejecutar Docker'
on: push
jobs:
  saludar:
     runs-on: ubuntu-latest
     name: 'Tarea para saludarme'
     steps:
      - name: 'Ejectuar la accion del docker'
        id: hola
        uses: mongegapper/ina-docker-mg/action@main
        with:
          quien: 'Lucho'
      - name: 'Mostrar la hora obtenida'
        run: echo "La hora obtenida fue ${{ steps.hola.outputs.hora }}"
