name: 'Flujo con docker-compose'
on: push
jobs:
  probar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ls -l  
      - name: 'Iniciar docker-compose'
        run: docker-compose -f docker_compose.yml up
      - name: 'Listar los contenendores en ejecucion'
        run:  docker ps -a
      - name: 'Mostar la bitacora de inicio '
        run: docker logs basedatos
